site_name: Neotoma System Documentation
site_description: Comprehensive documentation for the Neotoma database and infrastructure
site_author: Simon J. Goring
site_url: https://open.neotomadb.org/system_documentation

repo_url: https://github.com/NeotomaDB/system_documentation
repo_name: NeotomaDB/system_documentation
edit_uri: edit/main/docs

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  palette:
    # Light mode
    - scheme: default
      primary: grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit

extra_css:
  - docs/assets/styles.css

plugins:
  - search
  - tags
  - autorefs
  - mermaid2
  - bibtex:
      bib_file: "docs/assets/references.bib"
  - privacy
  - awesome-pages
  - macros:
      module_name: docs/macros
      include_dir: docs
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - swagger-ui-tag

markdown_extensions:
  - toc:
      permalink: '#'
      separator: "_"
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Database:
      - Introduction: database/index.md
      - Neotoma Database History: database/neotoma_history.md
      - Design Concepts:
        - Overview: database/design_concepts.md
        - Security: database/security.md
        - User Management: database/user_management.md
        - Schemas and the Holding Tank: database/schemas.md
        - Functions: database/functions.md
        - Queries: database/queries.md
        - Extensions: database/extensions.md
      - Connecting to Neotoma: database/connection.md
      - Table Overview: database/overview.md
  - API:
      - Overview: api/index.md
      - Neotoma API:
        - Quick Start: api/quickstart.md
        - Authentication: api/authentication.md
        - Endpoints by Table: api/endpoints/by-table.md
        - Design Concepts:
          - Overview: api/overview.md
          - Security: api/security.md
          - Adding API Endpoints:
            - Endpoints from the Database: api/building/dbhelpers.md
            - External Endpoints: api/building/external.md
      - Tilia:
        - Quick Start: api/tilia/quickstart.md
        - Authentication: api/tilia/authentication.md
        - Endpoints by Table: api/tilia/endpoints.md
        - Design Concepts:
          - Overview: api/tilia/overview.md
          - Adding API Endpoints: api/tilia/building.md
  - Landing Pages:
      - Overview: landingpages/index.md
      - Design Concepts:
        - Components: landingpages/components.md
        - Authentication: landingpages/orcid.md
  - Explorer:
    - Overview: explorer/index.md
    - Design Concepts: explorer/design.md
  - AWS Infrastructure:
      - Introduction: aws/introduction.md
      - Design Concepts:
        - Overview: aws/concepts/index.md
        - Production and Development: aws/concepts/developing.md
        - Troubleshooting: aws/concepts/troubleshooting.md
      - Services:
        - S3 Services: aws/services/s3storage/index.md
        - AppRunner: aws/services/apprunner/index.md
        - RDS: aws/services/rds/index.md
        - Route 53: aws/services/route53/index.md
        - Cron Jobs: aws/services/batch/index.md
        - Containers: aws/services/ecr/index.md
        - CloudWatch: aws/services/cloudwatch/index.md
  - GitHub:
      - Introduction: github/index.md
      - Design Concepts:
        - Overview: github/concepts/index.md
        - R Programming: github/concepts/rcode.md
        - Python: github/concepts/python.md
        - JavaScript: github/concepts/javascript.md
        - SQL: github/concepts/SQL.md
      - Services:
        - Landing Pages: github/landingpages.md
        - DataBUS: github/databus.md
        - NeotomaPyDOI: github/neotomapydoi.md
  - Runbooks: runbooks/index.md
  - Reports: reports/data_quality_report.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NeotomaDB
      name: Neotoma on Github

watch:
  - docs/macros.py